name: Contactame Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network
    container:
      image: node

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v1
      - name: Install and test
        run: |
          npm install

        env:
          # use mongodb for the host here because we have specified a container for the job.
          # If we were running the job on the VM this would be localhost
          APP_PORT: 5000
          NODE_ENV: testing
          DB_HOST: mongodb
          DB_PORT: ${{ job.services.mongodb.ports[27017] }}
          DB_NAME: ${{ secrets.DOCKER_USER }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Docker build
        run: docker build -t contactame-back .
      - name: Tags
        run: |
          docker tag contactame-back ${{ secrets.DOCKER_USER }}/contactame-back:${{ github.sha }}
          docker tag contactame-back ${{ secrets.DOCKER_USER }}/contactame-back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/contactame-back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/contactame-back:latest